version: "2"
services:
  web:
    build: ./web
    ports:
      - "10080:10080"
    links:
      - memcached
      - local-mysql5.6
    depends_on:
      - local-mysql5.6
    container_name: local_web
    volumes:
      - "./web/project:/home/www/project"
      - "./web/share:/home/www/share"
      - "./web/log:/home/log"
      - "./web/httpd_conf:/usr/local/apache/conf/virtual"
    tty: true

  memcached:
    image: "memcached:1.4"
    container_name: some-memcached

  local-mysql5.6:
    image: mysql:5.6
    container_name: local-mysql5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect="SET NAMES utf8" --innodb_file_per_table=1 --innodb_file_format=BARRACUDA
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - "../mysql:/var/lib/mysql"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - local-mysql5.6
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=local-mysql5.6
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - "../phpmyamin/session:/session"
